language: ruby
  rvm:
    - 2.3.1
  script:
    - RAILS_ENV=test bundle exec rake db:schema:load --trace
    - bundle exec rake db:test:prepare
    - bundle exec rspec spec/
  branches:
    only:
      - master
  before_script:
  - psql -c 'create database my_app_test;' -U postgres
  - rake db:migrate
